kind: pipeline
name: test

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: deamos/osp-hub-api
    auto_tag: true
  when:
    event:
      - push
- name: publish-test
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: docker_server
    port: 22
    username:
      from_secret: username
    password:
      from_secret: password
    script:
      - cd /compose-files/open-streaming-platform-hub-api && sudo /bin/bash ./update.sh
  when:
    event:
      - push