version: '2.4'

networks:
  osphub:
    external: false
  web:
    external: true
services:
  osphub_db:
    image: mariadb
    restart: unless-stopped
    mem_limit: 256m
    memswap_limit: 512m
    mem_reservation: 256m
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /srv/docker/osphub-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=REPLACEOSPROOTDBPASSWORD
      - MYSQL_PASSWORD=REPLACEOSPDBPASSWORD
      - MYSQL_DATABASE=osp
      - MYSQL_USER=osp
    networks:
      - osphub
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 1m
      timeout: 1s
      retries: 5
      start_period: 30s
  
  osp_hub:
    image: deamos/osp-hub-api:latest
    restart: unless-stopped
    mem_limit: 2048m
    memswap_limit: 2304m
    mem_reservation: 2048m
    ports:
      - 5718:5000/tcp
    labels:
      traefik.enable: true
      traefik.http.routers.osphubapi.rule: Host(`hubapi.internal.divby0.net`)
      traefik.port: 5000
    environment:
      - OSP_HUB_DB=mysql+pymysql://osp:REPLACEOSPDBPASSWORD@osphub_db/osp
      # - TZ=ETC/UTC
    networks:
      - osphub
      - web
    depends_on:
      - osphub_db
