version: '2.4'

networks:
  osphub:
    external: false
  web:
    external: true
services:
  osphub_db:
    image: mariadb
    restart: unless-stopped
    mem_limit: 256m
    memswap_limit: 512m
    mem_reservation: 256m
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /srv/docker/osphub-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=REPLACEOSPROOTDBPASSWORD
      - MYSQL_PASSWORD=REPLACEOSPDBPASSWORD
      - MYSQL_DATABASE=osp
      - MYSQL_USER=osp
    networks:
      - osphub
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 1m
      timeout: 1s
      retries: 5
      start_period: 30s
  
  osphub_redis:
    image: redis
    restart: unless-stopped
    mem_limit: 128m
    memswap_limit: 256m
    mem_reservation: 128m
    networks:
      - osphub
  
  osp_hub:
    image: deamos/osp-hub-api:latest
    restart: unless-stopped
    mem_limit: 1024m
    memswap_limit: 2304m
    mem_reservation: 1024m
    ports:
      - 5000/tcp
    labels:
      traefik.enable: true
      traefik.http.routers.osphubapi.rule: Host(`hubapi.internal.divby0.net`)
      traefik.port: 5000555
    environment:
      - OSP_CORE_TYPE=hub
      - OSP_REDIS_HOST=osphub_redis
      - OSP_REDIS_PORT=6379
      - OSP_REDIS_PASSWORD=
      - OSP_HUB_DB=mysql+pymysql://osp:REPLACEOSPDBPASSWORD@osphub_db/osp
      # - TZ=ETC/UTC
    networks:
      - osphub
      - web
    depends_on:
      - osphub_db
      - osphub_redis
  
  osp_hub_celery:
    image: deamos/osp-hub-api:latest
    restart: unless-stopped
    mem_limit: 1024m
    memswap_limit: 2304m
    mem_reservation: 1024m
    ports:
      - 5000/tcp
    environment:
      - OSP_CORE_TYPE=celery
      - OSP_REDIS_HOST=osphub_redis
      - OSP_REDIS_PORT=6379
      - OSP_REDIS_PASSWORD=
      - OSP_HUB_DB=mysql+pymysql://osp:REPLACEOSPDBPASSWORD@osphub_db/osp
      # - TZ=ETC/UTC
    networks:
      - osphub
      - web
    depends_on:
      - osphub_db
      - osphub_redis

  osp_hub_celery_beat:
    image: deamos/osp-hub-api:latest
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 2304m
    mem_reservation: 512m
    ports:
      - 5000/tcp
    environment:
      - OSP_CORE_TYPE=beat
      - OSP_REDIS_HOST=osphub_redis
      - OSP_REDIS_PORT=6379
      - OSP_REDIS_PASSWORD=
      - OSP_HUB_DB=mysql+pymysql://osp:REPLACEOSPDBPASSWORD@osphub_db/osp
      # - TZ=ETC/UTC
    networks:
      - osphub
      - web
    depends_on:
      - osphub_db
      - osphub_redis

  osp_hub_celery_flower:
    image: deamos/osp-hub-api:latest
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 2304m
    mem_reservation: 512m
    ports:
      - 51012:5555/tcp
    environment:
      - OSP_CORE_TYPE=flower
      - OSP_REDIS_HOST=osphub_redis
      - OSP_REDIS_PORT=6379
      - OSP_REDIS_PASSWORD=
      - OSP_HUB_DB=mysql+pymysql://osp:REPLACEOSPDBPASSWORD@osphub_db/osp
      # - TZ=ETC/UTC
    networks:
      - osphub
      - web
    depends_on:
      - osphub_db
      - osphub_redis