"""empty message

Revision ID: 02218ebaf23a
Revises: 578a6f76ff78
Create Date: 2022-07-25 15:41:11.180494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02218ebaf23a'
down_revision = '578a6f76ff78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('serverConfirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'serverConfirmed')
    # ### end Alembic commands ###
