"""empty message

Revision ID: 4fe71ac14b01
Revises: 02218ebaf23a
Create Date: 2022-07-31 11:50:49.445345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe71ac14b01'
down_revision = '02218ebaf23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.String(length=255), nullable=True),
    sa.Column('serverChannelLoc', sa.String(length=255), nullable=True),
    sa.Column('streamerId', sa.Integer(), nullable=True),
    sa.Column('streamPage', sa.String(length=255), nullable=True),
    sa.Column('streamName', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail', sa.String(length=1024), nullable=True),
    sa.Column('gifThumbnail', sa.String(length=1024), nullable=True),
    sa.Column('topic', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.Integer(), nullable=True),
    sa.Column('topicId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['serverId'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    op.drop_table('stream')
    # ### end Alembic commands ###
