"""empty message

Revision ID: 578a6f76ff78
Revises: 
Create Date: 2022-07-10 19:10:58.178350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578a6f76ff78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apikey', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.String(length=255), nullable=True),
    sa.Column('serverAddress', sa.String(length=255), nullable=True),
    sa.Column('serverProtocol', sa.String(length=5), nullable=True),
    sa.Column('serverActive', sa.Boolean(), nullable=True),
    sa.Column('serverLastUpdate', sa.DateTime(), nullable=True),
    sa.Column('serverName', sa.String(length=255), nullable=True),
    sa.Column('serverToken', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serverAddress'),
    sa.UniqueConstraint('serverId'),
    sa.UniqueConstraint('serverToken')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverId', sa.Integer(), nullable=True),
    sa.Column('channelName', sa.String(length=255), nullable=True),
    sa.Column('channelDescription', sa.String(length=2048), nullable=True),
    sa.Column('channelOwnerUsername', sa.String(length=256), nullable=True),
    sa.Column('channelOwnerPicture', sa.String(length=255), nullable=True),
    sa.Column('channelLocation', sa.String(length=255), nullable=True),
    sa.Column('channelViewers', sa.Integer(), nullable=True),
    sa.Column('channelLive', sa.Boolean(), nullable=True),
    sa.Column('channelLastUpdated', sa.DateTime(), nullable=True),
    sa.Column('channelImage', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['serverId'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel')
    op.drop_table('server')
    op.drop_table('apikey')
    # ### end Alembic commands ###
