"""empty message

Revision ID: 60a3355ee347
Revises: 0a6beba889e8
Create Date: 2023-04-24 12:57:26.570163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a3355ee347'
down_revision = '0a6beba889e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelUUID', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channelUUID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned_channel')
    # ### end Alembic commands ###
