"""empty message

Revision ID: f0d788f7b5a9
Revises: e5eba289550b
Create Date: 2023-04-16 13:06:35.447769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d788f7b5a9'
down_revision = 'e5eba289550b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('serverImage', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'serverImage')
    # ### end Alembic commands ###
